In [21]:
import pandas as pd
import numpy as np
import ploty.graph_objects as go
import ploty.colors as colors
pio.templates.default = "plotly_white"

ModuleNotFoundError: No module named 'ploty'

In [22]:
data=pd.read_csv("D:\Ecomerce data analysis python\Sample - Superstore.csv",encoding= 'latin-1')

In [3]:
data

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [4]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [5]:
data.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

# converting date columns

In [11]:
data['Order Date']= pd.to_datetime(data['Order Date'])
data['Ship Date']= pd.to_datetime(data['Ship Date'])

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(3), object(14)
memory usage: 1.6+ MB

In [12]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [14]:
data['Order Month']= data['Order Date'].dt.month
data['Order Year']= data['Order Date'].dt.year
data['Order Day Of Week']=data['Order Date'].dt.dayofweek

In [15]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order Month,Order Year,Order Day Of Week
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,11,2016,1
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,11,2016,1
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,6,2016,6
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,10,2015,6
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,10,2015,6

# Monthly Sales Analysis

In [16]:
sales_by_month = data.groupby('Order Month')['Sales'].sum().reset_index()

In [17]:
sales_by_month

    Order Month        Sales
0             1   94924.8356
1             2   59751.2514
2             3  205005.4888
3             4  137762.1286
4             5  155028.8117
5             6  152718.6793
6             7  147238.0970
7             8  159044.0630
8             9  307649.9457
9            10  200322.9847
10           11  352461.0710
11           12  325293.5035

# 1. Top 10 Customers by Lifetime Value

In [28]:
top_customers = (
    data.groupby(['Customer ID', 'Customer Name'])['Sales']
        .sum()
        .reset_index()
        .sort_values(by='Sales', ascending=False)
        .head(10)
)

top_customers

    Customer ID       Customer Name      Sales
700    SM-20320         Sean Miller  25043.050
741    TC-20980        Tamara Chand  19052.218
621    RB-19360        Raymond Buch  15117.339
730    TA-21385        Tom Ashbrook  14595.620
6      AB-10105       Adrian Barton  14473.571
434    KL-16645        Ken Lonsdale  14175.229
669    SC-20095        Sanjit Chand  14142.334
327    HL-15040        Hunter Lopez  12873.298
683    SE-20110        Sanjit Engle  12209.438
131    CC-12370  Christopher Conant  12129.072

In [ ]:
# Insight:These customers generate the highest revenue and should be targeted for loyalty programs.

# 2. Top 10 Customers by Profit

In [29]:
top_profit_customers = (
    data.groupby('Customer Name')['Profit']
        .sum()
        .reset_index()
        .sort_values(by='Profit', ascending=False)
        .head(10)
)

top_profit_customers

            Customer Name     Profit
730          Tamara Chand  8981.3239
622          Raymond Buch  6976.0959
671          Sanjit Chand  5757.4119
334          Hunter Lopez  5622.4292
6           Adrian Barton  5444.8055
757          Tom Ashbrook  4703.7883
157  Christopher Martinez  3899.8904
431         Keith Dawkins  3038.6254
35            Andy Reiter  2884.6208
194         Daniel Raglin  2869.0760

In [ ]:
Insight:These customers contribute the most to overall profitability.

# 3. Top 10 Cities by Sales

In [32]:
top_cities = (
    data.groupby('City')['Sales']
        .sum()
        .reset_index()
        .sort_values(by='Sales', ascending=False)
        .head(10)
)

top_cities

              City        Sales
329  New York City  256368.1610
266    Los Angeles  175851.3410
452        Seattle  119540.7420
438  San Francisco  112669.0920
374   Philadelphia  109077.0130
207        Houston   64504.7604
80         Chicago   48539.5410
437      San Diego   47521.0290
216   Jacksonville   44713.1830
464    Springfield   43054.3420

In [ ]:
Insight:These cities represent the strongest markets.

# 4. Top 10 Cities by Profit

In [61]:
top_profit_cities = (
    data.groupby('City')['Profit']
        .sum()
        .reset_index()
        .sort_values(by='Profit', ascending=False)
        .head(10)
)

top_profit_cities

              City      Profit
329  New York City  62036.9837
266    Los Angeles  30440.7579
452        Seattle  29156.0967
438  San Francisco  17507.3854
123        Detroit  13181.7908
233      Lafayette  10018.3876
215        Jackson   7581.6828
21         Atlanta   6993.6629
300    Minneapolis   6824.5846
437      San Diego   6377.1960

# 5. Loss-Making Cities

In [63]:
category_profit = (
    data.groupby('Category')['Profit']
        .sum()
        .reset_index()
        .sort_values(by='Profit', ascending=False)
)

category_profit

          Category       Profit
2       Technology  145454.9481
1  Office Supplies  122490.8008
0        Furniture   18451.2728

# 6. Sales by Category

In [35]:
category_sales = (
    data.groupby('Category')['Sales']
        .sum()
        .reset_index()
        .sort_values(by='Sales', ascending=False)
)

category_sales

          Category        Sales
2       Technology  836154.0330
0        Furniture  741999.7953
1  Office Supplies  719047.0320

# 7. Profit by Category

In [62]:
loss_cities = (
    data.groupby('City')['Profit']
        .sum()
        .reset_index()
        .sort_values(by='Profit')
        .head(10)
)

loss_cities

             City      Profit
374  Philadelphia -13837.7674
207       Houston -10153.5485
434   San Antonio  -7299.0502
241     Lancaster  -7239.0684
80        Chicago  -6654.5688
60     Burlington  -3622.8772
109        Dallas  -2846.5257
375       Phoenix  -2790.8832
24         Aurora  -2691.7386
216  Jacksonville  -2323.8350

# 8. Sales by Sub-Category

In [37]:
subcategory_sales = (
    data.groupby('Sub-Category')['Sales']
        .sum()
        .reset_index()
        .sort_values(by='Sales', ascending=False)
)

subcategory_sales

   Sub-Category        Sales
13       Phones  330007.0540
5        Chairs  328449.1030
14      Storage  223843.6080
16       Tables  206965.5320
3       Binders  203412.7330
11     Machines  189238.6310
0   Accessories  167380.3180
6       Copiers  149528.0300
4     Bookcases  114879.9963
1    Appliances  107532.1610
9   Furnishings   91705.1640
12        Paper   78479.2060
15     Supplies   46673.5380
2           Art   27118.7920
7     Envelopes   16476.4020
10       Labels   12486.3120
8     Fasteners    3024.2800

# 9. Profit by Sub-Category

In [38]:
subcategory_profit = (
    data.groupby('Sub-Category')['Profit']
        .sum()
        .reset_index()
        .sort_values(by='Profit', ascending=False)
)

subcategory_profit

   Sub-Category      Profit
6       Copiers  55617.8249
13       Phones  44515.7306
0   Accessories  41936.6357
12        Paper  34053.5693
3       Binders  30221.7633
5        Chairs  26590.1663
14      Storage  21278.8264
1    Appliances  18138.0054
9   Furnishings  13059.1436
7     Envelopes   6964.1767
2           Art   6527.7870
10       Labels   5546.2540
11     Machines   3384.7569
8     Fasteners    949.5182
15     Supplies  -1189.0995
4     Bookcases  -3472.5560
16       Tables -17725.4811

# 10. Monthly Sales Trend

In [58]:
data['Order Date'] = pd.to_datetime(data['Order Date'])

monthly_sales = (
    data.groupby(data['Order Date'].dt.to_period('M'))['Sales']
        .sum()
)

monthly_sales

Order Date
2014-01     14236.8950
2014-02      4519.8920
2014-03     55691.0090
2014-04     28295.3450
2014-05     23648.2870
2014-06     34595.1276
2014-07     33946.3930
2014-08     27909.4685
2014-09     81777.3508
2014-10     31453.3930
2014-11     78628.7167
2014-12     69545.6205
2015-01     18174.0756
2015-02     11951.4110
2015-03     38726.2520
2015-04     34195.2085
2015-05     30131.6865
2015-06     24797.2920
2015-07     28765.3250
2015-08     36898.3322
2015-09     64595.9180
2015-10     31404.9235
2015-11     75972.5635
2015-12     74919.5212
2016-01     18542.4910
2016-02     22978.8150
2016-03     51715.8750
2016-04     38750.0390
2016-05     56987.7280
2016-06     40344.5340
2016-07     39261.9630
2016-08     31115.3743
2016-09     73410.0249
2016-10     59687.7450
2016-11     79411.9658
2016-12     96999.0430
2017-01     43971.3740
2017-02     20301.1334
2017-03     58872.3528
2017-04     36521.5361
2017-05     44261.1102
2017-06     52981.7257
2017-07     45264.4160
2017-08     63120.8880
2017-09     87866.6520
2017-10     77776.9232
2017-11    118447.8250
2017-12     83829.3188
Freq: M, Name: Sales, dtype: float64

# 11. Yearly Sales Trend

In [59]:
yearly_sales = (
    data.groupby(data['Order Date'].dt.year)['Sales']
        .sum()
)

yearly_sales

Order Date
2014    484247.4981
2015    470532.5090
2016    609205.5980
2017    733215.2552
Name: Sales, dtype: float64

# 12. Region Wise Sales

In [41]:
region_sales = (
    data.groupby('Region')['Sales']
        .sum()
        .reset_index()
        .sort_values(by='Sales', ascending=False)
)

region_sales

    Region        Sales
3     West  725457.8245
1     East  678781.2400
0  Central  501239.8908
2    South  391721.9050

# 13. Region Wise Profit

In [42]:
region_profit = (
    data.groupby('Region')['Profit']
        .sum()
        .reset_index()
        .sort_values(by='Profit', ascending=False)
)

region_profit

    Region       Profit
3     West  108418.4489
1     East   91522.7800
2    South   46749.4303
0  Central   39706.3625

# 14. Average Order Value

In [43]:
aov = (
    data.groupby('Order ID')['Sales']
        .sum()
        .mean()
)

print(aov)

458.61466566180883

# 15. Most Sold Products

In [44]:
top_products = (
    data.groupby('Product Name')['Quantity']
        .sum()
        .reset_index()
        .sort_values(by='Quantity', ascending=False)
        .head(10)
)

top_products

                                           Product Name  Quantity
1499                                            Staples       215
1493                                    Staple envelope       170
537                                   Easy-staple paper       150
1500                            Staples in misc. colors        86
942                          KI Adjustable-Height Table        74
259                             Avery Non-Stick Binders        71
1511                            Storex Dura Pro Binders        71
699   GBC Premium Transparent Covers with Diagonal L...        67
1450         Situations Contoured Folding Chairs, 4/Set        64
1497                         Staple-based wall hangings        62

# 16. Most Profitable Products

In [45]:
profitable_products = (
    data.groupby('Product Name')['Profit']
        .sum()
        .reset_index()
        .sort_values(by='Profit', ascending=False)
        .head(10)
)

profitable_products

                                           Product Name      Profit
404               Canon imageCLASS 2200 Advanced Copier  25199.9280
650   Fellowes PB500 Electric Punch Plastic Comb Bin...   7753.0390
805                Hewlett Packard LaserJet 3310 Copier   6983.8836
400                  Canon PC1060 Personal Laser Copier   4570.9347
787   HP Designjet T520 Inkjet Large Format Printer ...   4094.9766
165                   Ativa V4110MDD Micro-Cut Shredder   3772.9461
19     3D Systems Cube Printer, 2nd Generation, Magenta   3717.9714
1276  Plantronics Savi W720 Multi-Device Wireless He...   3696.2820
895                Ibico EPK-21 Electric Binding System   3345.2823
1840                  Zebra ZM400 Thermal Label Printer   3343.5360

# 17. Discount Impact on Profit

In [46]:
data[['Discount','Profit']].corr()

          Discount    Profit
Discount  1.000000 -0.219487
Profit   -0.219487  1.000000

In [ ]:
Insight:Negative correlation indicates discounts reduce profitability.

# 18. Average Shipping Time

In [47]:
data['Ship Date'] = pd.to_datetime(data['Ship Date'])

data['Shipping Days'] = (
    data['Ship Date'] - data['Order Date']
).dt.days

data['Shipping Days'].mean()

np.float64(3.958174904942966)

In [ ]:
Insight:Measures operational efficiency.

# 19. Segment Wise Revenue

In [48]:
segment_sales = (
    data.groupby('Segment')['Sales']
        .sum()
        .reset_index()
        .sort_values(by='Sales', ascending=False)
)

segment_sales

       Segment         Sales
0     Consumer  1.161401e+06
1    Corporate  7.061464e+05
2  Home Office  4.296531e+05

# 20. Segment Wise Profit

In [60]:
segment_profit = (
    data.groupby('Segment')['Profit']
        .sum()
        .reset_index()
        .sort_values(by='Profit', ascending=False)
)

segment_profit

       Segment       Profit
0     Consumer  134119.2092
1    Corporate   91979.1340
2  Home Office   60298.6785

In [ ]:
Insight:Shows which customer segment is most profitable.

# Advanced Questions

# 21. RFM Customer Segmentation

In [51]:
snapshot_date = data['Order Date'].max()

rfm = data.groupby('Customer ID').agg({
    'Order Date': lambda x: (snapshot_date - x.max()).days,
    'Order ID': 'nunique',
    'Sales': 'sum'
})

rfm.columns = ['Recency','Frequency','Monetary']

rfm.head()

             Recency  Frequency  Monetary
Customer ID
AA-10315         184          5  5563.560
AA-10375          19          9  1056.390
AA-10480         259          4  1790.512
AA-10645          55          6  5086.935
AB-10015         415          3   886.156

In [ ]:
Insight:Identifies loyal and at-risk customers.

# 22. Pareto Analysis (80-20 Rule)

In [52]:
customer_sales = (
    data.groupby('Customer Name')['Sales']
        .sum()
        .sort_values(ascending=False)
)

(customer_sales.cumsum()/customer_sales.sum())*100

Customer Name
Sean Miller          1.090155
Tamara Chand         1.919522
Raymond Buch         2.577598
Tom Ashbrook         3.212964
Adrian Barton        3.843016
                      ...
Roy Skaria          99.998111
Mitch Gastineau     99.998840
Carl Jackson        99.999559
Lela Donovan        99.999790
Thais Sissman      100.000000
Name: Sales, Length: 793, dtype: float64

In [ ]:
Insight:Checks if 20% customers generate 80% revenue.

# 23. Customer Retention Analysis

In [53]:
repeat_customers = (
    data.groupby('Customer ID')['Order ID']
        .nunique()
)

repeat_customers[repeat_customers > 1].count()

np.int64(781)

In [ ]:
Insight:Measures customer loyalty.

# 24. High Discount Loss Analysis

In [54]:
high_discount = data[data['Discount'] > 0.3]

high_discount.groupby('Category')['Profit'].sum()

Category
Furniture         -43782.4392
Office Supplies   -47140.1376
Technology        -34084.2018
Name: Profit, dtype: float64

In [55]:
Insight:Evaluates whether discounts hurt profitability.

SyntaxError: invalid syntax (1316042305.py, line 1)

# 25. Profit Margin Analysis

In [56]:
profit_margin = (
    data['Profit'].sum() /
    data['Sales'].sum()
) * 100

print(profit_margin)

12.467217240315605

In [ ]:
Insight:Measures overall business profitability.